function outdata = lookup_var2read()


% Cell array with the following columns:
% 1: instrument, 2: list of variables to be included (names in database), 
% 3: corresponding variable names uniform data
% !! The order of variable names determines the order in which the
% variables are written to netcdf files later on! Make sure, that first one
% is time and second one is height (if applicable). In general, put
% dimensions first.
%outdata(1,:) = {'radar',{'time','height','dbz','dv','ldr','sw','radar_flag'},...
%                    {'time','height','dBZ','VEL','LDR','RMS','data_flag'}}; % + lat, lon, alt?
                
outdata(1,:) = {'radar',{'time','height','dbz','ldr','radar_flag'},...
                    {'time','height','dBZ','LDR','data_flag'}}; % + lat, lon, alt?                

%outdata(2,:) = {'dropsondes',...
%                    {'time','height','sonde_number','height','dir','pa'},...
%                   {'time','height','sonde_number','height','dir','p'}};
% outdata(2,:) = {'dropsondes',...
%                     {'sonde_number','height','wdir','lat','lon','humr','pa','hur',... %statt wdir verwende ich mal dir, da das mal file steht
%                     'wspeed','ta','theta','theta_e','theta_v','tv','u','v','launch_time'},...
%                     {'sonde_number','height','wdir','lat','lon','mr','p','rh',...
%                     'wspd','ta','theta','theta_e','theta_v','tv','u','v','launch_time'}};
outdata(2,:) = {'dropsondes',...
                    {'sonde_number','height','wdir','lat','lon','pa','hur',... %statt wdir verwende ich mal dir, da das mal file steht
                    'wspeed','ta','base_time', 'sonde_time'},...
                    {'sonde_number','height','dir','lat','lon','p','rh',...
                    'spd','ta','launch_time', 'sonde_time'}};
                
outdata(3,:) = {'radiometer',{'time','tb','freq_sb','interpolate_flag',},...%,'freq_sb'
                    {'time','tb','frequency','interpolate_flag',}};%,'frequency'
                
outdata(4,:) = {'bahamas',{'zsl','lat','lon'},...
                    {'altitude','lat','lon'}};

% outdata(4,:) = {'bahamas',{'time','zsl','speed_gnd','heading','lat','lon','humr','pa',...
%                             'pitch','hur','roll','ta','theta','u','v','vel','w'},...
%                     {'time','altitude','speed_gnd','heading','lat','lon','mr','p',...
%                             'pitch','rh','roll','ta','theta','u','v','vel','w'}};