function make_radarNoiseMask(flightdates_mask,outfile,type)

% Input 'type' can either be 'noise' or 'calibration'

% Load noise info data (generated by hand, using lookForNoiseManually
radar_mask;

% flightdates_mask = get_campaignDates('2016');

noiseMask = cell(length(flightdates_mask),1);

for i=1:length(flightdates_mask)
    
    % Find entries that match the flight date and that contain 'noise'
    indUse = find(strcmp(flightdates_mask{i},mask(:,1)) & strcmp(type,mask(:,4)));
    filepath = listFiles([getPathPrefix  getCampaignFolder(flightdates_mask{i}) 'all_nc/*radar*' ...
                            flightdates_mask{i} '*.nc'],'fullpath');

    uniTime = unixtime2sdn(ncread(filepath{end},'time'));
    uniHeight = ncread(filepath{end},'height');

    noiseMask{i} = zeros(length(uniHeight),length(uniTime));
        
    if ~isempty(indUse)
        
%         flightdate = mask{i,1};

       
        
        for j=1:length(indUse)
            diffTime_start = abs(mask{indUse(j),2}(1)-uniTime);
            indTime_start = find(diffTime_start==min(diffTime_start));
            
            
            diffTime_end = abs(mask{indUse(j),2}(2)-uniTime);
            indTime_end = find(diffTime_end==min(diffTime_end));
            
            noiseMask{i}(:,indTime_start:indTime_end) = 1;
        end
    
    end
    
    noiseMask{i} = logical(noiseMask{i});
end

if strcmp(type,'calibration')
    calibrationMask = noiseMask;
    outvar = 'calibrationMask';
else
    outvar = 'noiseMask';
end

if exist(outfile,'file')
    save(outfile,outvar,'-append')
else
    save(outfile,outvar,'-v7.3')
end